export const DUMMY = [
  {
    id: 1,
    title: "남자친구 생일 선물 추천해주세요 20대 초반인데 운동 좋아해요",
    content: "다음 달이 남자친구 생일인데 뭘 사줄지 모르겠어요. 평소에 헬스 다니고 러닝도 좋아하는데 예산은 5만원 이내로 생각하고 있어요.",
    memberNickname: "김민지",
    viewCount: 128,
    likeCount: 24,
    answerCount: 7,
    acceptedAnswerId: 3,
    tagNames: ["생일", "남성", "5만원이하", "20대"],
    situation: "생일",
    target: "남자친구",
    ageGroup: "20대",
    budget: "5만원대",
    createdAt: "2026-06-30T11:00:00",
  },
  {
    id: 2,
    title: "부모님 결혼기념일 선물 고민입니다",
    content: "올해 부모님 결혼 30주년인데 뭔가 특별한 걸 드리고 싶어요. 두 분이 여행을 좋아하셔서 여행 관련 선물도 좋을 것 같고요.",
    memberNickname: "이재원",
    viewCount: 85,
    likeCount: 11,
    answerCount: 3,
    acceptedAnswerId: null,
    tagNames: ["기념일", "부모님", "10만원이하"],
    situation: "기념일",
    target: "부모님",
    ageGroup: "50대 이상",
    budget: "10만원대",
    createdAt: "2026-06-30T08:00:00",
  },
  {
    id: 3,
    title: "친한 여사친 취업 선물 뭐가 좋을까요",
    content: "친구가 드디어 취업했는데 축하 선물을 하고 싶어요. 실용적인 걸 좋아하는 스타일이에요.",
    memberNickname: "박준호",
    viewCount: 62,
    likeCount: 8,
    answerCount: 2,
    acceptedAnswerId: null,
    tagNames: ["취업", "여성", "3만원이하", "20대"],
    situation: "취업",
    target: "친구",
    ageGroup: "20대",
    budget: "3만원대",
    createdAt: "2026-06-29T15:00:00",
  },
  {
    id: 4,
    title: "여자친구한테 크리스마스 선물 뭐가 좋을까요",
    content: "크리스마스가 얼마 안 남았는데 여자친구한테 뭘 줘야 할지 모르겠어요. 뷰티 제품 좋아하고 예산은 3만원대로 생각 중이에요.",
    memberNickname: "최유진",
    viewCount: 210,
    likeCount: 45,
    answerCount: 12,
    acceptedAnswerId: 8,
    tagNames: ["크리스마스", "여성", "3만원대", "20대"],
    situation: "크리스마스",
    target: "여자친구",
    ageGroup: "20대",
    budget: "3만원대",
    createdAt: "2026-06-29T10:00:00",
  },
  {
    id: 5,
    title: "직장 상사 어버이날 선물 추천 부탁드려요",
    content: "직장 상사분이 부모님 어버이날 선물 고민하시는데 제가 대신 찾아드리고 싶어요. 10만원대 예산이에요.",
    memberNickname: "정소연",
    viewCount: 44,
    likeCount: 3,
    answerCount: 1,
    acceptedAnswerId: null,
    tagNames: ["어버이날", "부모님", "10만원대"],
    situation: "어버이날",
    target: "직장동료",
    ageGroup: "40대",
    budget: "10만원대",
    createdAt: "2026-06-28T20:00:00",
  },
  {
    id: 6,
    title: "고등학교 졸업하는 남동생 선물",
    content: "남동생이 이번에 고등학교 졸업하는데 의미 있는 선물을 해주고 싶어요. 평소에 게임 좋아하고 예산은 5만원대로 생각 중이에요.",
    memberNickname: "한지수",
    viewCount: 77,
    likeCount: 15,
    answerCount: 5,
    acceptedAnswerId: null,
    tagNames: ["졸업", "남성", "5만원대", "10대"],
    situation: "졸업",
    target: "친구",
    ageGroup: "10대",
    budget: "5만원대",
    createdAt: "2026-06-28T14:00:00",
  },
];
