export const NOTIFICATION_TYPE = {
  ANSWER_ACCEPTED: "ANSWER_ACCEPTED",

  QUESTION_LIKED: "QUESTION_LIKED",
  ANSWER_LIKED: "ANSWER_LIKED",
  COMMENT_LIKED: "COMMENT_LIKED",

  QUESTION_ANSWER_CREATED: "QUESTION_ANSWER_CREATED",
  QUESTION_COMMENT_CREATED: "QUESTION_COMMENT_CREATED",
  ANSWER_COMMENT_CREATED: "ANSWER_COMMENT_CREATED",
};