spring:
  application:
    name: foryou

  devtools:
    add-properties: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    xyz.abcganada.foryou.auth: DEBUG
    xyz.abcganada.foryou.member: DEBUG

image:
  upload:
    path: /tmp/foryou/images
    url-prefix: http://localhost:8080/images

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
