spring:
  application:
    name: foryou

  devtools:
    add-properties: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

image:
  upload:
    path: /tmp/foryou/images
    url-prefix: http://localhost:8080/images

